language: node_js
node_js:
  - node
before_install:
    - npm install mocha -g
after_success: 
    - mocha testear.js --exit
deploy:
  provider: heroku
  api_key:
    secure: Wo2AtuXtLnzs/FrIv7U6CSh/mx7lvQ9m2kt4lhN7X8kc9xCeR7Cw3zBQxkEUCsPvO+Yyywnzya79HdPfj5ifRZSeKQgrTTZGmjWvaEGNUPW7T5e3L1fSs/wcWDts88L78tMsGdTjmW1TnYAU46WJ89OHYnhgnJYJHmEunKp97u5h9hODYZeiIOGAEW/KY+KqCXNYkSffLeop6IttjhTEpUfRU54Z/Mk3vtfbuWilh9xlIwGTCGahpb64ImS0MnYTxNRFGgZuW0akZmq33q+lHoDifIh1HT7mPZcaZYLiU6We6A6FXLp85ukbDcvH1Q8Mh0LiQcLs8JEkb2Chf/taFImSFkDqMsN3Prgc+BFJErIf72/mE6478HDKDeCHcekqkkPJ7B8yQBZcIv1OkEQJISqpBWZrzPI+8LKJVmy2nQVn2OMpHNvMzoM+1N/gPrbSi/uS5d6yPUUyShcnmxrLcNBKn427VY0DUELr5HA63rZCvEw15fZ7BKPvBZCgl20xwv9YXK62Tfa0223UdrlfhAvWmm4me4tZE1AiBUH4QMZWPBmYS4NnIo88A3aVXXDVG5zhGCd/wgENBe/T7p4zCn31yjJdLARC+p3BwU4yg136nrtk/pU/5APQCTiN/6y0Yp+yiMm9cU6NDOuKZaOC28j62b3WlkfZr+30eVoIJAA=
  app: calprenob
