branches:
  only:
    - master
language: node_js
node_js:
  - node
install:
  - npm install mocha
  - npm install supertest
  - npm install express
  - npm install mongodb
  - npm install bunyan
deploy:
  provider: heroku
  api_key:
    secure: fyf5/WVXozN52cEari1oeDwJmh5EO2mER6v5aSiYmlH3QcXVPn1BT4Tnr4tDsR2cxgpc6J59fJOjkcZllrSxGkUOUQLwf3uau6jIxXyZtJLRiJmtBLdDuHVIuvhdOUUtY7TiPvHR7Q+U38ayI1JDfBTd4fPPjQEG8NYqleMHc04LF5y9hI/m2IZ4Ir2qlt/nskqTURQ7EwTSalqiy93gfNoC9X1T17z5NmLJ2xjTJ0i6W88QrwcnYXbTK+QjI7+aB9AKKPxHvRNiB0sbc+bwJ4+in4egqSuYrrWcImabTyd3rdmpP5YAR5tWPqzbkQrMUVchBP0pbc6G8klqBezUXgvSNIQcSSEyvGdRgH4wjis9z9I7SC5aFSIC/J1pQerTbakIdOWqHRsRALmTxCwBFE3gsQI5Idct+p/PxYsZwx2YbvtVAvobf5+IY3Ft2y1Jb+ffGMPATfiUY01HlTf2Ds6He1ivCllBj/apR/PVQAPuv0vA3AGON7y5swf8WIwEkMlTdJAETMqLBGTUEXoLS7aohgLPGWs3f5/p2wn/xEVdoItvgZEEEPeOgz0Jk2vWEVYWMxLTJOVA1uNeig1Llv4Y+R6XoqbsHk4i3yQbCNnsTwcyrFsIAJFJy0MbFWKZ6zzkDE1Omox+flrkdQ39uEigqbksY8mq1pVpxzDB5e4=
  strategy: git
  app: evening-anchorage-70354
  on:
    repo: jrtrillo/proyecto_cc
